#Testing environment
version: "3.9"
services: 
  postgres:
    image: postgres:13.4
    hostname: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks: 
      internal: 
        aliases:
          - postgres
    volumes: 
      - "${PWD}/initdb:/docker-entrypoint-initdb.d"
  node:
    build: .
    ports: 
      - "8080:80"
      - "2222:22"
      - "9229:9229"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_FLAGS=--enable-source-maps --inspect-brk=0.0.0.0:9229 
      - LOG_LEVEL=${LOG_LEVEL}
      - TEST_GUILD=${TEST_GUILD}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_ID=888963470601617409 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal
networks: 
  internal: